<?php

namespace App;


class ConversationFaker
{

    public function fakeConversation($mediaId)
    {
        if ($mediaId == '2') {
            return '{
                    "status": "OK",
                    "code": 200,
                    "widgetID": "C",
                    "startDate": "2016-06-01 00:00:00",
                    "endDate": "2016-10-01 23:59:59",
                    "mediaID": "1,2,3,4,5",
                    "brandID": "",
                    "topicID": "",
                    "sentiment": "",
                    "icapt": "",
                    "text": "",
                    "param": {
                    },
                    "order": "",
                    "currPage": 1,
                    "totalPage": 161,
                    "rpp": 25,
                    "totalRow": 25,
                    "project": {
                        "pid": "1715362982016",
                        "pname": "Gubernur DKI"
                    },
                    "message": [
                        {
                            "dtime": "2016-10-01 11:37:22",
                            "uniqId": "1125151623",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "dlvr.it",
                            "msgId": "782076920074637312",
                            "profileUrl": "http://twitter.com/JSJkrysx",
                            "city": null,
                            "klout": "http://klout.com/JSJkrysx",
                            "mentionMap": "http://mentionmapp.com/#user-JSJkrysx",
                            "messageUrl": "http://twitter.com/JSJkrysx/status/782076920074637312",
                            "screeName": "JSJkrysx",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/WuucqXaLJn"
                        },
                        {
                            "dtime": "2016-10-01 11:37:24",
                            "uniqId": "1125151620",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "dlvr.it",
                            "msgId": "782076928689700866",
                            "profileUrl": "http://twitter.com/Calm_Luhan",
                            "city": null,
                            "klout": "http://klout.com/Calm_Luhan",
                            "mentionMap": "http://mentionmapp.com/#user-Calm_Luhan",
                            "messageUrl": "http://twitter.com/Calm_Luhan/status/782076928689700866",
                            "screeName": "Calm_Luhan",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/GeOCsprAO4"
                        },
                        {
                            "dtime": "2016-10-01 11:37:24",
                            "uniqId": "1125151610",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "dlvr.it",
                            "msgId": "782076929541152768",
                            "profileUrl": "http://twitter.com/choAOA",
                            "city": null,
                            "klout": "http://klout.com/choAOA",
                            "mentionMap": "http://mentionmapp.com/#user-choAOA",
                            "messageUrl": "http://twitter.com/choAOA/status/782076929541152768",
                            "screeName": "choAOA",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/hhcTVC4uru"
                        },
                        {
                            "dtime": "2016-10-01 11:37:25",
                            "uniqId": "1125151607",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782076929985826818",
                            "profileUrl": "http://twitter.com/ratih_Anggi033",
                            "city": null,
                            "klout": "http://klout.com/ratih_Anggi033",
                            "mentionMap": "http://mentionmapp.com/#user-ratih_Anggi033",
                            "messageUrl": "http://twitter.com/ratih_Anggi033/status/782076929985826818",
                            "screeName": "ratih_Anggi033",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok: Tim pemenangan akan banyak mengusung ... https://t.co/m9xYv9nCkK #RanoKarnoHRSMundur"
                        },
                        {
                            "dtime": "2016-10-01 11:37:25",
                            "uniqId": "1125151602",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "dlvr.it",
                            "msgId": "782076931353174016",
                            "profileUrl": "http://twitter.com/gdmien",
                            "city": null,
                            "klout": "http://klout.com/gdmien",
                            "mentionMap": "http://mentionmapp.com/#user-gdmien",
                            "messageUrl": "http://twitter.com/gdmien/status/782076931353174016",
                            "screeName": "gdmien",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/B2fY50if8d"
                        },
                        {
                            "dtime": "2016-10-01 11:37:26",
                            "uniqId": "1125151598",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "dlvr.it",
                            "msgId": "782076935073435649",
                            "profileUrl": "http://twitter.com/dasomkiddo",
                            "city": null,
                            "klout": "http://klout.com/dasomkiddo",
                            "mentionMap": "http://mentionmapp.com/#user-dasomkiddo",
                            "messageUrl": "http://twitter.com/dasomkiddo/status/782076935073435649",
                            "screeName": "dasomkiddo",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/A4V6COVBs4"
                        },
                        {
                            "dtime": "2016-10-01 11:37:38",
                            "uniqId": "1125151596",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782076985757474818",
                            "profileUrl": "http://twitter.com/Nagari_Tandikat",
                            "city": null,
                            "klout": "http://klout.com/Nagari_Tandikat",
                            "mentionMap": "http://mentionmapp.com/#user-Nagari_Tandikat",
                            "messageUrl": "http://twitter.com/Nagari_Tandikat/status/782076985757474818",
                            "screeName": "Nagari_Tandikat",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok: Tim pemenangan akan banyak mengusung fakta-fakta ke... https://t.co/v2d1bUZ2ja #news"
                        },
                        {
                            "dtime": "2016-10-01 11:37:39",
                            "uniqId": "1125151594",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782076990912278528",
                            "profileUrl": "http://twitter.com/tandikek_utara",
                            "city": null,
                            "klout": "http://klout.com/tandikek_utara",
                            "mentionMap": "http://mentionmapp.com/#user-tandikek_utara",
                            "messageUrl": "http://twitter.com/tandikek_utara/status/782076990912278528",
                            "screeName": "tandikek_utara",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok: Tim pemenangan akan banyak mengusung fakta-fakta ke... https://t.co/aGD9ngqTiV #news"
                        },
                        {
                            "dtime": "2016-10-01 11:37:41",
                            "uniqId": "1125151592",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "dlvr.it",
                            "msgId": "782077000550756353",
                            "profileUrl": "http://twitter.com/MYUNGSEQ",
                            "city": null,
                            "klout": "http://klout.com/MYUNGSEQ",
                            "mentionMap": "http://mentionmapp.com/#user-MYUNGSEQ",
                            "messageUrl": "http://twitter.com/MYUNGSEQ/status/782077000550756353",
                            "screeName": "MYUNGSEQ",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/iNfk5YmfYn"
                        },
                        {
                            "dtime": "2016-10-01 11:37:58",
                            "uniqId": "1125151589",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "Put your button on any page! ",
                            "msgId": "782077069656223744",
                            "profileUrl": "http://twitter.com/HelmiHelmimoze",
                            "city": null,
                            "klout": "http://klout.com/HelmiHelmimoze",
                            "mentionMap": "http://mentionmapp.com/#user-HelmiHelmimoze",
                            "messageUrl": "http://twitter.com/HelmiHelmimoze/status/782077069656223744",
                            "screeName": "HelmiHelmimoze",
                            "text": "Sejenak nonton Videotron  @VIVAcoid: Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/Fs8pcTBD8W "
                        },
                        {
                            "dtime": "2016-10-01 11:39:39",
                            "uniqId": "1125151587",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782077492756484096",
                            "profileUrl": "http://twitter.com/ArifhakimHK",
                            "city": null,
                            "klout": "http://klout.com/ArifhakimHK",
                            "mentionMap": "http://mentionmapp.com/#user-ArifhakimHK",
                            "messageUrl": "http://twitter.com/ArifhakimHK/status/782077492756484096",
                            "screeName": "ArifhakimHK",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok: Tim pemenangan akan banyak mengusung fakta-fakta keberhas... https://t.co/pBHUwAobmb"
                        },
                        {
                            "dtime": "2016-10-01 11:39:41",
                            "uniqId": "1125151585",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782077502269247488",
                            "profileUrl": "http://twitter.com/game_mbel",
                            "city": null,
                            "klout": "http://klout.com/game_mbel",
                            "mentionMap": "http://mentionmapp.com/#user-game_mbel",
                            "messageUrl": "http://twitter.com/game_mbel/status/782077502269247488",
                            "screeName": "game_mbel",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok: Tim pemenangan akan banyak mengusung fakta-fakta keberhas... https://t.co/88fjGZ97AO"
                        },
                        {
                            "dtime": "2016-10-01 11:39:47",
                            "uniqId": "1125151582",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782077527854489600",
                            "profileUrl": "http://twitter.com/riyan_bahlul",
                            "city": null,
                            "klout": "http://klout.com/riyan_bahlul",
                            "mentionMap": "http://mentionmapp.com/#user-riyan_bahlul",
                            "messageUrl": "http://twitter.com/riyan_bahlul/status/782077527854489600",
                            "screeName": "riyan_bahlul",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/ey8K9ift3h"
                        },
                        {
                            "dtime": "2016-10-01 11:40:57",
                            "uniqId": "1125151579",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "Google",
                            "msgId": "782077822240223233",
                            "profileUrl": "http://twitter.com/Wolfcrime",
                            "city": null,
                            "klout": "http://klout.com/Wolfcrime",
                            "mentionMap": "http://mentionmapp.com/#user-Wolfcrime",
                            "messageUrl": "http://twitter.com/Wolfcrime/status/782077822240223233",
                            "screeName": "Wolfcrime",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok: Tim pemenangan akan banyak mengusung fakta-fakta… https://t.co/S2stPNYbsY #VivaNews"
                        },
                        {
                            "dtime": "2016-10-01 11:41:23",
                            "uniqId": "1125151576",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782077930327248897",
                            "profileUrl": "http://twitter.com/KicauGalau_1",
                            "city": null,
                            "klout": "http://klout.com/KicauGalau_1",
                            "mentionMap": "http://mentionmapp.com/#user-KicauGalau_1",
                            "messageUrl": "http://twitter.com/KicauGalau_1/status/782077930327248897",
                            "screeName": "KicauGalau_1",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/g3IdpwDrPl (VIVAnews)"
                        },
                        {
                            "dtime": "2016-10-01 11:41:32",
                            "uniqId": "1125151573",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782077968440885248",
                            "profileUrl": "http://twitter.com/bantentraffic",
                            "city": null,
                            "klout": "http://klout.com/bantentraffic",
                            "mentionMap": "http://mentionmapp.com/#user-bantentraffic",
                            "messageUrl": "http://twitter.com/bantentraffic/status/782077968440885248",
                            "screeName": "bantentraffic",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/fu5VfZDOMO"
                        },
                        {
                            "dtime": "2016-10-01 11:41:46",
                            "uniqId": "1125151572",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782078025345019904",
                            "profileUrl": "http://twitter.com/bokuranoashiato",
                            "city": null,
                            "klout": "http://klout.com/bokuranoashiato",
                            "mentionMap": "http://mentionmapp.com/#user-bokuranoashiato",
                            "messageUrl": "http://twitter.com/bokuranoashiato/status/782078025345019904",
                            "screeName": "bokuranoashiato",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/6aPuuMxkFW"
                        },
                        {
                            "dtime": "2016-10-01 11:41:46",
                            "uniqId": "1125151568",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782078026406170624",
                            "profileUrl": "http://twitter.com/NewsViva_",
                            "city": null,
                            "klout": "http://klout.com/NewsViva_",
                            "mentionMap": "http://mentionmapp.com/#user-NewsViva_",
                            "messageUrl": "http://twitter.com/NewsViva_/status/782078026406170624",
                            "screeName": "NewsViva_",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/Lw4PidVZCv"
                        },
                        {
                            "dtime": "2016-10-01 11:43:06",
                            "uniqId": "1125151566",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782078360579088384",
                            "profileUrl": "http://twitter.com/Arisfivedragon",
                            "city": null,
                            "klout": "http://klout.com/Arisfivedragon",
                            "mentionMap": "http://mentionmapp.com/#user-Arisfivedragon",
                            "messageUrl": "http://twitter.com/Arisfivedragon/status/782078360579088384",
                            "screeName": "Arisfivedragon",
                            "text": "#SinagaNews Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok: Tim pemenangan akan banyak mengusung fakta-fa... https://t.co/jsh27tmC1z"
                        },
                        {
                            "dtime": "2016-10-01 11:43:11",
                            "uniqId": "1125151564",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782078383131725824",
                            "profileUrl": "http://twitter.com/Dickys_",
                            "city": null,
                            "klout": "http://klout.com/Dickys_",
                            "mentionMap": "http://mentionmapp.com/#user-Dickys_",
                            "messageUrl": "http://twitter.com/Dickys_/status/782078383131725824",
                            "screeName": "Dickys_",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok: Tim pemenangan akan banyak mengusung fakta-fakta keberhas... https://t.co/F3zEOBO0qD"
                        },
                        {
                            "dtime": "2016-10-01 11:43:16",
                            "uniqId": "1125151561",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782078405047037952",
                            "profileUrl": "http://twitter.com/Berita_Lainnya",
                            "city": null,
                            "klout": "http://klout.com/Berita_Lainnya",
                            "mentionMap": "http://mentionmapp.com/#user-Berita_Lainnya",
                            "messageUrl": "http://twitter.com/Berita_Lainnya/status/782078405047037952",
                            "screeName": "Berita_Lainnya",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/guYwQQzNfn #VillarrealWeak"
                        },
                        {
                            "dtime": "2016-10-01 11:43:42",
                            "uniqId": "1125151482",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782078514849734656",
                            "profileUrl": "http://twitter.com/Kurougane",
                            "city": null,
                            "klout": "http://klout.com/Kurougane",
                            "mentionMap": "http://mentionmapp.com/#user-Kurougane",
                            "messageUrl": "http://twitter.com/Kurougane/status/782078514849734656",
                            "screeName": "Kurougane",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok: Tim pemenangan akan banyak mengusung fakta-fakta keberhas... https://t.co/tYuwJvEJfd"
                        },
                        {
                            "dtime": "2016-10-01 11:46:12",
                            "uniqId": "1125165953",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "Twitter Web Client",
                            "msgId": "782079142493691904",
                            "profileUrl": "http://twitter.com/Suka_kopi",
                            "city": null,
                            "klout": "http://klout.com/Suka_kopi",
                            "mentionMap": "http://mentionmapp.com/#user-Suka_kopi",
                            "messageUrl": "http://twitter.com/Suka_kopi/status/782079142493691904",
                            "screeName": "Suka_kopi",
                            "text": "RT @MeiiRiieChen: Jakarta jadi jarang macet gegara jokowi-ahok (ʃ⌣ƪ) #OctoberWish"
                        },
                        {
                            "dtime": "2016-10-01 11:47:06",
                            "uniqId": "1125165919",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782079369359466496",
                            "profileUrl": "http://twitter.com/DionoHd",
                            "city": null,
                            "klout": "http://klout.com/DionoHd",
                            "mentionMap": "http://mentionmapp.com/#user-DionoHd",
                            "messageUrl": "http://twitter.com/DionoHd/status/782079369359466496",
                            "screeName": "DionoHd",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok https://t.co/WyqdIi7b8D"
                        },
                        {
                            "dtime": "2016-10-01 11:47:12",
                            "uniqId": "1125165914",
                            "mediaId": "2",
                            "sentimentId": "-1",
                            "readMarkId": "0",
                            "ptype": "twitterfeed",
                            "msgId": "782079394252587008",
                            "profileUrl": "http://twitter.com/YesiskhaSW",
                            "city": null,
                            "klout": "http://klout.com/YesiskhaSW",
                            "mentionMap": "http://mentionmapp.com/#user-YesiskhaSW",
                            "messageUrl": "http://twitter.com/YesiskhaSW/status/782079394252587008",
                            "screeName": "YesiskhaSW",
                            "text": "Kurangi Macet dan Banjir, Jadi Modal Kampanye Ahok: Tim pemenangan akan banyak mengusung fakta-fakta keberhas... https://t.co/nmXN2V6vMN"
                        }
                    ]
                }';
        } else {
            return '{
                  "status": "OK",
                  "code": 200,
                  "widgetID": "C",
                  "startDate": "2016-08-01 00:00:00",
                  "endDate": "2016-08-31 23:59:59",
                  "mediaID": "1,2,3,4,5,6,9,10",
                  "brandID": "",
                  "topicID": "",
                  "sentiment": "1,0,-1",
                  "icapt": "",
                  "text": "",
                  "param": {
                    "day": "0",
                    "user": ""
                  },
                  "order": " ORDER BY sentiment asc, dtime desc",
                  "currPage": 1,
                  "totalPage": 1,
                  "rpp": 25,
                  "totalRow": 16,
                  "project": {
                    "pid": "2253502522013",
                    "pname": "susu"
                  },
                  "message": [
                    {
                      "dtime": "2016-08-28 15:52:29",
                      "uniqId": "15185862",
                      "mediaId": "5",
                      "sentimentId": "0",
                      "readMarkId": "0",
                      "author": "M. Fathur Rahman K.",
                      "videoTitle": "Joget Cokelat Frisian Flag",
                      "videoUrl": "http://www.youtube.com/watch?v=hXtKvOdJCTc"
                    },
                    {
                      "dtime": "2016-08-28 14:23:21",
                      "uniqId": "15185665",
                      "mediaId": "5",
                      "sentimentId": "0",
                      "readMarkId": "0",
                      "author": "M. Fathur Rahman K.",
                      "videoTitle": "Joget Cokelat Frisian Flag #NikmatnyaCokelat",
                      "videoUrl": "http://www.youtube.com/watch?v=VwYg45-9kAU"
                    },
                    {
                      "dtime": "2016-08-28 09:47:21",
                      "uniqId": "15181422",
                      "mediaId": "5",
                      "sentimentId": "0",
                      "readMarkId": "0",
                      "author": "agung budiantoro",
                      "videoTitle": "Anak dancow",
                      "videoUrl": "http://www.youtube.com/watch?v=NRuB32xDrSw"
                    },
                    {
                      "dtime": "2016-08-28 09:39:16",
                      "uniqId": "15181395",
                      "mediaId": "5",
                      "sentimentId": "0",
                      "readMarkId": "0",
                      "author": "ayu nurjanah",
                      "videoTitle": "joged  frisian flag.. seru",
                      "videoUrl": "http://www.youtube.com/watch?v=rQkq70CvDpA"
                    },
                    {
                      "dtime": "2016-08-21 18:43:38",
                      "uniqId": "15061748",
                      "mediaId": "5",
                      "sentimentId": "0",
                      "readMarkId": "0",
                      "author": "Ria Novita",
                      "videoTitle": "Joget Cokelat Frisian Flag",
                      "videoUrl": "http://www.youtube.com/watch?v=zjFtmBeO95E"
                    },
                    {
                      "dtime": "2016-08-21 15:43:34",
                      "uniqId": "15061749",
                      "mediaId": "5",
                      "sentimentId": "0",
                      "readMarkId": "0",
                      "author": "Riyanto Yosafat",
                      "videoTitle": "project pop live show 2015 at Frisian Flag Indonesia",
                      "videoUrl": "http://www.youtube.com/watch?v=6cYo_kIEAaE"
                    },
                    {
                      "dtime": "2016-08-21 05:39:04",
                      "uniqId": "15061750",
                      "mediaId": "5",
                      "sentimentId": "0",
                      "readMarkId": "0",
                      "author": "Amanda Juwita Sumirat",
                      "videoTitle": "Frisian flag milk challenge",
                      "videoUrl": "http://www.youtube.com/watch?v=3qLpr33CbAo"
                    },
                    {
                      "dtime": "2016-08-21 00:20:06",
                      "uniqId": "15061781",
                      "mediaId": "5",
                      "sentimentId": "0",
                      "readMarkId": "0",
                      "author": "Rhey Chantique",
                      "videoTitle": "Fashion show cassual by dancow",
                      "videoUrl": "http://www.youtube.com/watch?v=mLelkxMMpvw"
                    },
                    {
                      "dtime": "2016-08-14 16:47:29",
                      "uniqId": "14910351",
                      "mediaId": "5",
                      "sentimentId": "1",
                      "readMarkId": "0",
                      "author": "Sevenplus Creative Studio",
                      "videoTitle": "Frisian Flag Indonesia (FFI) - Nutrisi Sesuai dengan Manfaat Lebih!",
                      "videoUrl": "http://www.youtube.com/watch?v=9lTUiOQ6sl8"
                    },
                    {
                      "dtime": "2016-08-14 16:42:41",
                      "uniqId": "14910352",
                      "mediaId": "5",
                      "sentimentId": "1",
                      "readMarkId": "0",
                      "author": "Sevenplus Creative Studio",
                      "videoTitle": "Frisian Flag Indonesia (FFI) - Saat Momennya Tiba, Siapkah Kita Jadi Orang Tua",
                      "videoUrl": "http://www.youtube.com/watch?v=7WuJZQYEMTk"
                    },
                    {
                      "dtime": "2016-08-14 16:37:41",
                      "uniqId": "14910353",
                      "mediaId": "5",
                      "sentimentId": "1",
                      "readMarkId": "0",
                      "author": "Sevenplus Creative Studio",
                      "videoTitle": "Frisian Flag Indonesia (FFI) - Momen 9 Bulan Terindah dalam Hidupku & Istriku",
                      "videoUrl": "http://www.youtube.com/watch?v=MD7DCUSladQ"
                    },
                    {
                      "dtime": "2016-08-14 13:17:50",
                      "uniqId": "14906821",
                      "mediaId": "5",
                      "sentimentId": "1",
                      "readMarkId": "0",
                      "author": "Rpdhs Ponsel",
                      "videoTitle": "Iklan dankow",
                      "videoUrl": "http://www.youtube.com/watch?v=tPOOFbRjRHs"
                    },
                    {
                      "dtime": "2016-08-14 12:10:18",
                      "uniqId": "14906560",
                      "mediaId": "5",
                      "sentimentId": "1",
                      "readMarkId": "0",
                      "author": "queena queena",
                      "videoTitle": "Makan - makan Chips ahoy , Permen ,Susu ultra milk , Oreo mini good",
                      "videoUrl": "http://www.youtube.com/watch?v=pjbWIsUhB98"
                    },
                    {
                      "dtime": "2016-08-14 09:49:21",
                      "uniqId": "14904134",
                      "mediaId": "5",
                      "sentimentId": "1",
                      "readMarkId": "0",
                      "author": "Bianca Kristabel",
                      "videoTitle": "Permen Es Milo  { Seger }",
                      "videoUrl": "http://www.youtube.com/watch?v=_9MlsCqAqV8"
                    },
                    {
                      "dtime": "2016-08-14 06:41:23",
                      "uniqId": "14902560",
                      "mediaId": "5",
                      "sentimentId": "1",
                      "readMarkId": "0",
                      "author": "Ratna Indria Sari 02",
                      "videoTitle": "Rubben fael action in dancow",
                      "videoUrl": "http://www.youtube.com/watch?v=Wy51RBRsL-0"
                    },
                    {
                      "dtime": "2016-08-14 04:02:35",
                      "uniqId": "14901291",
                      "mediaId": "5",
                      "sentimentId": "1",
                      "readMarkId": "0",
                      "author": "Vicky Laurentina",
                      "videoTitle": "Event Promosi Susu oleh Dancow",
                      "videoUrl": "http://www.youtube.com/watch?v=Zx_1_qfNDLs"
                    }
                  ]
                }';
        }
    }
}